version: '3.8'

services:
  couchbase:
    build:
      context: ./couchbase
    container_name: couchbase
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=todo
      - COUCHBASE_BUCKET_PASSWORD=
    ports:
      - 8091-8093:8091-8093
      - 11210-11211:11210-11211
    volumes:
      - todo-data:/opt/couchbase/var
      - ./couchbase/configure-node.sh:/opt/couchbase/configure-node.sh
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8091/ui/index.html" ]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 120s
    networks:
      todo-network:
        aliases:
          - couchbase1
    command: [ "sh", "-c", "couchbase-server & sleep 15 && sh /opt/couchbase/configure-node.sh && tail -f /dev/null" ]

  todo-list-app:
    image: oznklnc/todoapp
    container_name: todo-list-app
    ports:
      - 8080:8080
    depends_on:
      - couchbase
    environment:
      - COUCHBASE_HOST=couchbase1
    networks:
      - todo-network
    restart: always

volumes:
  todo-data:

networks:
  todo-network:
    driver: bridge