version: '3.8'

services:
  couchbase1:
    build:
      context: ./couchbase
    container_name: couchbase1
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
      - COUCHBASE_BUCKET=todo
      - COUCHBASE_BUCKET_PASSWORD=
    ports:
      - 8091-8093:8091-8093
      - 11210-11211:11210-11211
    volumes:
      - couchbase1-data:/opt/couchbase/var
      - ./couchbase/configure-node.sh:/opt/couchbase/configure-node.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8091/ui/index.html"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 120s
    networks:
      - couchbase-network
    command: ["sh", "-c", "couchbase-server & sleep 15 && sh /opt/couchbase/configure-node.sh && tail -f /dev/null"]

volumes:
  couchbase1-data:

networks:
  couchbase-network:
    driver: bridge